gems:
  - jekyll-redirect-from
  - kramdown
name: Rafa Gómez
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: /:title/
url: "http://rafa.wtf"
description: Co-Founder and CTO at @CodelyTV
excerpt_separator: <!--more-->
