gems:
  - jekyll-redirect-from
  - kramdown
name: Rafa Gómez
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
permalink: /:title/
url: "http://rafa.im"
description: Software engineer at @letgo.
excerpt_separator: <!--more-->
