baseURL = "https://rafa.wtf/"
title = "Rafa Gómez Casas | Cofundador de Codely"
languageCode = "es-ES"

disableHugoGeneratorInject = true
defaultContentLanguage = "es"
preserveTaxonomyNames = true
paginate = 100

[permalinks]
  charlas = "/charlas/:filename"
  frases = "/frases/:filename"
  articulos = "/:filename"
  etc = "/:filename"

[params]
  description = "Artículos, vídeos, recursos y tutoriales sobre Desarrollo Web, Frontend, Performance Web ⚡️, Javascript ☕️, React ⚛️ y CSS 🎨"
  image = "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/320/apple/271/victory-hand_270c-fe0f.png"

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    tabWidth = 2

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
